[build]
  #Le decimos a Netlify dónde tiene que compilar React/Next.js
  base = "client"
  publish = ".next"
  command = "npm run build"
  
[[plugins]]
  #para next dinamico
  package = "@netlify/plugin-nextjs"

[functions]
  #'directory' en su propio bloque para poder salir correctamente de 'client'
  directory = "../api"
  
[functions."*"]
  included_files = ["../api/**"]

[[redirects]]
  #Para que el front se comunique con el back 
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
