[build]
  #Le decimos a Netlify dónde tiene que compilar React/Next.js
  base = "client"
  publish = "out/server/app"
  command = "npm run build"

  [functions]
  #'directory' en su propio bloque para poder salir correctamente de 'client'
  directory = "../api"

[[redirects]]
  #Para que el front se comunique con el back 
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
